Repository selsa-inube/inubekit-textfield, pull requests merged in 2024-03, with the labels that each got.

#3 Refactor component to use new tokens, and component dependencies
  package-lock.json
  package.json
  src/Textfield/index.tsx
  src/Textfield/props.ts
  src/Textfield/stories/Textfield.stories.tsx
  src/Textfield/stories/TextfieldController.tsx
  src/Textfield/styles.js
  vite.config.ts
Labels: major

#4 Publish new version 2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#5 Remove "valid" value from status prop
  src/Textfield/props.ts
  src/Textfield/stories/TextfieldController.tsx
Labels: patch

#6 Publish new version 2.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#7 Adjust and export interfaces
  src/Textfield/index.tsx
  src/Textfield/props.ts
  src/index.ts
Labels: minor

#8 Update inubekit/textfield to storybook v8
  package-lock.json
  package.json
Labels: dependencies

#9 Publish new version 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
